# Generated by Django 5.0.7 on 2024-07-19 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0007_patient_prescription_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='Frequency',
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monday', models.BooleanField(default=False)),
                ('Tuesday', models.BooleanField(default=False)),
                ('Wednesday', models.BooleanField(default=False)),
                ('Thursday', models.BooleanField(default=False)),
                ('Friday', models.BooleanField(default=False)),
                ('Saturday', models.BooleanField(default=False)),
                ('Sunday', models.BooleanField(default=False)),
                ('MedicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Frequencies', to='healthcare_app.medication')),
            ],
        ),
    ]
