# Generated by Django 5.0.7 on 2024-07-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0008_remove_medication_frequency_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='Dosage',
            field=models.PositiveIntegerField(),
        ),
    ]
