# Generated by Django 5.0.7 on 2024-07-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0009_alter_medication_dosage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='PrescriptionID',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='GuardianID',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='PatientID',
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
