# Generated by Django 5.0.7 on 2024-07-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0012_guardian_chatid_patient_chatid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='chatID',
            new_name='ChatID',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='chatID',
            new_name='ChatID',
        ),
    ]
