# Generated by Django 5.0.7 on 2024-07-21 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthcare_app', '0012_guardian_chatid_patient_chatid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('CurrentDateTime', models.DateTimeField(auto_now_add=True)),
                ('NotificationTime', models.TimeField()),
                ('isTaken', models.BooleanField(default=False)),
                ('TimeTaken', models.TimeField(blank=True, null=True)),
                ('GuardianID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.guardian')),
                ('MedicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.medication')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['GuardianID'], name='telegram_bo_Guardia_55a9b2_idx'), models.Index(fields=['PatientID'], name='telegram_bo_Patient_799def_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicationReminderForToday',
            fields=[
                ('MedicationReminderForTodayID', models.AutoField(primary_key=True, serialize=False)),
                ('GuardianChatID', models.CharField(max_length=255)),
                ('PatientChatID', models.CharField(max_length=255)),
                ('MedicationName', models.CharField(max_length=255)),
                ('Dosage', models.PositiveIntegerField()),
                ('Label', models.TextField()),
                ('NotificationTime', models.TimeField()),
                ('isTaken', models.BooleanField(default=False)),
                ('TimeTaken', models.TimeField(blank=True, default=None, null=True)),
                ('GuardianID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.guardian')),
                ('MedicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.medication')),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_app.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['NotificationTime'], name='telegram_bo_Notific_422626_idx')],
            },
        ),
    ]
