# Generated by Django 5.0.7 on 2024-08-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminderfortoday',
            name='RemindGuardian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicationreminderfortoday',
            name='RemindPatient',
            field=models.BooleanField(default=False),
        ),
    ]
