# Generated by Django 5.0.7 on 2024-08-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_medicationreminderfortoday_remindguardian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationreminderfortoday',
            name='PatientName',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
